### PR TITLE
Fixes #6

### LINKED ISSUE #6: Mini map does not display cells with remaining monsters
When leaving a room that still contains monsters, the mini map does not display that cell appropriately.

Screenshot 2021-01-27 222708

### PR DESCRIPTION
**Pull request by wyskoj**

### CODE REVIEW

**Comment by jlachniet** [comment]
The bug is that it should be isVisible, not isListed

**Comment by wyskoj** [comment]
Well the CSS tag is "danger" so it should only apply to rooms with monsters in them. Rooms with food and weapons will be colored differently. But monsters overrides that so rooms with monsters and items will display as red. Plus this also just allows for general forwards compatibility for when more features are added to the game.

**Comment by jlachniet** [comment]
The css tag is outdated, but adding more colors is fine as well

**Comment by wyskoj** [comment]
Will open another PR adding new colors once this one is merged.

**Pull request merged**
